name: 'Wait for manual approval'
description: 'Create an issue and wait for an "approved" comment'
inputs:
  timeout-in-minutes:
    description: 'Waiting for approval timeout in minutes'
    required: true
    default: '10'
runs:
  using: "composite"
  steps:

    - run : env
      shell: bash
      if : ${{ env.RUNNER_DEBUG == 1 }}

    - name: Wait for manual approval
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('${{ github.action_path }}/index.js');
          await script(
            {
              github,
              context
            },
            {
              timeoutInMinutes: ${{ inputs.timeout-in-minutes }}
            }
          );