name: Test

on: 
  workflow_dispatch:
    inputs:    
      description:
        description: Description of the posted issue
        required: true
        default: This is an example of a description provided as input to the action.
      timeout:
        description: Timeout in minutes to wait for approval
        required: true
        default: "1"

jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:

      - name: Testing manual approval (see Issues)
        uses: scaleaq/manual-approve@v1.0.15
        with:
          description: ${{ github.event.inputs.description }}
          timeout-in-minutes: ${{ github.event.inputs.timeout }}